/*
 * This file was generated by the Gradle 'init' task.
 */

rootProject.name = "java-goof"
include(":todolist-core")
include(":todolist-web-common")
include(":todolist-web-struts")
include(":log4shell-client")
project(":todolist-core").projectDir = file("todolist-goof/todolist-core")
project(":todolist-web-common").projectDir = file("todolist-goof/todolist-web-common")
project(":todolist-web-struts").projectDir = file("todolist-goof/todolist-web-struts")
project(":log4shell-client").projectDir = file("log4shell-goof/log4shell-client")
