/*
 * This file was generated by the Gradle 'init' task.
 */

dependencies {
    implementation("org.springframework:spring-context:3.2.6.RELEASE")
    implementation("org.springframework:spring-orm:3.2.6.RELEASE")
    implementation("org.springframework:spring-aspects:3.2.6.RELEASE")
    implementation("cglib:cglib:2.2.2")
    implementation("org.aspectj:aspectjweaver:1.8.2")
    implementation("c3p0:c3p0:0.9.1.2")
    implementation("org.hsqldb:hsqldb:2.3.2")
    implementation("org.hibernate:hibernate-core:4.3.7.Final")
    implementation("org.hibernate:hibernate-entitymanager:4.3.7.Final")
    implementation("org.hibernate.javax.persistence:hibernate-jpa-2.0-api:1.0.1.Final")
    implementation("commons-collections:commons-collections:3.2.2")
    testImplementation("junit:junit:4.12")
    testImplementation("org.springframework:spring-test:3.2.6.RELEASE")
}

description = "Java Goof :: Todolist Goof :: Todolist Core"
