/*
 * This file was generated by the Gradle 'init' task.
 */

dependencies {
    implementation("com.fasterxml.jackson.core:jackson-core:${properties["java.goof.jackson_version"]}")
    implementation("com.fasterxml.jackson.core:jackson-databind:${properties["java.goof.jackson_version"]}")
    implementation("com.fasterxml.jackson.core:jackson-annotations:${properties["java.goof.jackson_version"]}")
    api(project(":todolist-core"))
    implementation("javax:javaee-web-api:7.0")
    implementation("javax.servlet:jstl:1.2")
    implementation("org.hibernate:hibernate-validator:4.3.1.Final")
}

description = "Java Goof :: Todolist Goof :: Todolist Web Common"
