/*
 * This file was generated by the Gradle 'init' task.
 */
dependencies {
    implementation("org.apache.logging.log4j:log4j-core:2.14.1")
    implementation("org.apache.logging.log4j:log4j-api:2.14.1")
}

group = "io.snyk"
description = "Java Goof :: Log4Shell Goof :: Log4Shell Client"
